### ISSUE TITLE
how do I use this

### ISSUE THREAD

**Issue by coronasaurus** [ManneN1/BigDebuffs-WotLK#1]
I downloaded the master and extracted it to the Addons folder, I'm playing on a 3.3.5 server. However the addon does not even show up under "AddOns" in the character selection and the /bd menu doesn't appear, either. Am I supposed to compile it first?
Please help me and thank you for making this awesome addon available on an older version of WoW.

**Comment by coronasaurus** [comment]
nvm i needed to only rename it, i feel dumb now

**Comment by ManneN1** [comment]
Please let me know if there are any bugs. I haven't used it extensively.
