### ISSUE TITLE
Debuff Icons on nameplates

### ISSUE THREAD

**Issue by Romain-P** [ManneN1/BigDebuffs-WotLK#10]
It should have debuff icons on top of nameplates

**Comment by ManneN1** [comment]
No, https://github.com/ManneN1/BigDebuffs-WotLK/issues/8.

Also, I don't help cheaters.

**Comment by Romain-P** [comment]
> No, #8.
> 
> Also, I don't help cheaters.

I don't need your help neither, just trying to help your trash retroport ;)

**Comment by Romain-P** [comment]
Also, it is possible to have debuffs w/o animation glitches while a nameplate movement, you just don't know how to do so. I might push a PR if I have time
