### ISSUE TITLE
Some CC's do not appear on portrait

### ISSUE THREAD

**Issue by slimeseason1** [ManneN1/BigDebuffs-WotLK#11]
![10_05_24_22_46_20s](https://github.com/user-attachments/assets/930c3463-59e9-4dc8-b1a5-d9d899055966)
![10_05_24_22_46_12s](https://github.com/user-attachments/assets/c83255ea-7a05-4c53-b6af-13d97d57e97c)
![Wow_2024_10_10_05_00_26s](https://github.com/user-attachments/assets/27f93f6a-f6ed-4b36-af95-e66df3cb9a2e)
![Wow_2024_10_10_05_00_57s](https://github.com/user-attachments/assets/83e463e4-6862-475f-8c9f-77aa2bfebbf3)

**Comment by ManneN1** [comment]
Should be resolved in https://github.com/ManneN1/BigDebuffs-WotLK/commit/b460a2e569725a876f1e37c50841ff479bad7a2e. Let me know if the issue remains.

**Comment by slimeseason1** [comment]
Fixed, thanks!
