### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by wiliardiaskhaby** [ManneN1/BigDebuffs-WotLK#3]
Message: Interface\AddOns\BigDebuffs\BigDebuffs.lua:829: attempt to index field '?' (a nil value)
Time: 11/20/20 08:56:04
Count: 1
Stack: Interface\AddOns\BigDebuffs\BigDebuffs.lua:829: in function `?'
...ffs\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147: in function <...ffs\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...ffs\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: in function `Fire'
...AddOns\BigDebuffs\libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\BigDebuffs\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\BigDebuffs\libs\AceAddon-3.0\AceAddon-3.0.lua:381
 SaveUnitFramePosition = <function> defined @Interface\AddOns\BigDebuffs\BigDebuffs.lua:532
 EnableModule = <function> defined @Interface\AddOns\BigDebuffs\libs\AceAddon-3.0\AceAddon-3.0.lua:346
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\BigDebuffs\libs\AceTimer-3.0\AceTimer-3.0.lua:161
 IterateEmbeds = <function> defined @Interface\AddOns\BigDebuffs\libs\AceAddon-3.0\AceAddon-3.0.lua:456
 SecureHookScript = <function> defined @Interface\AddOns\BigDebuffs\libs\AceHook-3.0\AceHook-3.0.lua:413
 GetUnitFromGUID = <function> defined @Interface\AddOns\BigDebuffs\BigDebuffs.lua:620
 RawHookScript = <function> defined @Interface\AddOns\BigDebuffs\libs\AceHook-3.0\AceHook-3.0.lua:398
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\BigDebuffs\libs\AceAddon-3.0\AceAddon-3.0.lua:423
 lastKnownStance = <table> {
 }
 InsertTestDebuff = <function> defined @Interface\AddOns\BigDebuffs\BigDebuffs.lua:543
 defaultModuleState = true
 IsEnabled = <function> defined @Interface\AddOns\BigDebuffs\libs\AceAddon-3.0\AceAddon-3.0.lua:465
 ScheduleTimer = <function> defined @Interface\AddOns\BigDebuffs\libs\AceTimer-3.0\AceTimer-3.0.lua:108
 DisableModule = <function> defined @Interface\AddOns\BigDebuffs\libs\AceAddon-3.0\AceAddon-3.0.lua:364
 RegisterMessage = <function> defined @Interface\AddOns\BigDebuffs\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 UnregisterMessage = <function> defined @Interface\AddOns\BigDebuffs\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:181
 frames = <table> {
 }
 IsHooked = <function> defined @Interface\AddOns\BigDebuffs\libs\AceHook-3.0\AceHook-3.0.lua:496
 PLAYER_FOCUS_CHANGED = <function> defined @Interface\AddOns\BigDebuffs\BigDebuffs.lua:878
 db = <table> {
 }
 UNIT_AURA = <function> defined @Interface\AddOns\BigDebuffs\BigDebuffs.lua:755
 SetEnabledState = <function> defined @Interface\AddOns\BigDebuffs\libs\AceAddon-3.0\AceAddon-3.0.lua:438
 Hook = <function> defined @Interface\AddOns\BigDebuffs\libs\AceHook-3.0\AceHook-3.0.lua:277
 enabledState = true
 COMBAT_LOG_EVENT_UNFILTERED = <function> defined @Interface\AddOns\BigDebuffs\BigDebuffs.lua:639
 RegisterEvent = <function> defined @Interface\AddOns\BigDebuffs\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 IterateModules = <function> defined @Interface\AddOns\BigDebuffs\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 RawHook = <function> defined @Interface\AddOns\BigDebuffs\libs\AceHook-3.0\AceHook-3.0.lua:316
 AttachUnitFrame = <function> defined @Interface\AddOns\BigDebuffs\BigDebuffs.lua:427
 OnInitialize = <function> defined @Interface\AddOns\BigDebuffs\BigDebuffs.lua:399
 NewModule = <function> defined @Interface\AddOns\BigDebuffs\libs\AceAddon-3.0\AceAddon-3.0.lua:255
 GetModule = <function> defined @Interface\AddOns\BigDebuffs\libs\AceAddon-3.0\AceAddon-3.0.lua:230
 UNIT_PET = <function> defined @Interface\AddOns\BigDebuffs\BigDebuffs.lua:886
 GetInterruptFor = <function> defined @Interface\AddOns\BigDebuffs\BigDebuffs.lua:726
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @Interface\AddOns\BigDebuffs\libs\AceTimer-3.0\AceTimer-3.0.lua:187
 UpdateSta

**Comment by ManneN1** [comment]
Thanks for the report.

Please check if the latest commit fixes the issue.
