### ISSUE TITLE
Update Backport & Spell List Update

### ISSUE THREAD

**Issue by Colerain** [ManneN1/BigDebuffs-WotLK#4]
The newer versions of BD for Retail/Classic have nameplate functionality. Could this functionality be backported to WotLK BD? 

Additionally, I've updated the spell list for use in the 39 bracket as the current one only works for level 80. It includes lower spell ranks and items that are not used commonly at level 80.

**Comment by ManneN1** [comment]
Hello,

Nameplates will not be implemented for now. Try using PlateBuffs for this functionality. This functionality on nameplates is fairly hard / impossible to add without making it buggy (cooldown animation starts flickering / not showing if the nameplate moves in WotLK).

W.r.t. your spell list, please add your BigDebuffs.lua file here.

**Comment by ManneN1** [comment]
Closing this as there has been no response.
