### ISSUE TITLE
I can't save

### ISSUE THREAD

**Issue by Onydda** [ManneN1/BigDebuffs-WotLK#5]
Hi, I can't save when i'm moving the cc frame of my party members idk how to save that it reset everytime i moved and cancel the "Toggle Test Mod"?

**Comment by ManneN1** [comment]
Thanks for your report.

Could you try with a clean installation of the AddOn (deleting any potential config files for BigDebuffs in the WTF folder) and give a step by step description on how to reproduce the issue?

**Comment by Onydda** [comment]
I did it and its the same thing, so when i open the addon with the command /bd or /bigdebuffs in Party Frames overlay the "Automatic Anchor" doesn't display the Party Frames when i click on "Toggle Test Mode" and when i switch the "Anchor" in "Manual" and click on "Toggle Test Mode" he show the Party Frames Anchor but when i moving them they doesn't stay at the place where i moved them and they reset i mean i can't save them when u click on "Toggle Test Mode" to Hide the Test Mode they reset. I hope i will help u with that and sorry if my english is bad.

**Comment by ManneN1** [comment]
I have tried to resolve the issue in the latest version (https://github.com/ManneN1/BigDebuffs-WotLK/commit/1421c5d8bb7c355533262f56b41000ea2eb13a05).

Please see if you can reproduce the issue, or if it has been fixed. If you do not respond within 7 days I will assume the issue has been fixed (as I am not able to reproduce it with this commit).

**Comment by Onydda** [comment]
Man its perfect thanks a lot ;)
