### ISSUE TITLE
Adding more spells

### ISSUE THREAD

**Issue by jonomurphy** [ManneN1/BigDebuffs-WotLK#7]
Apologies if wrong place, but is it possible to add more spells? Noticed Feral Druid's 'Pounce' and 'Maim' CC don't appear on the untiframes.

**Comment by jonomurphy** [comment]
Apologies! I can see that Maim and Pounce are listed, but they don't seem to work for me. I'll keep checking!

**Comment by ManneN1** [comment]
Hello,

I just made a level 80 Druid and tested both spells. They both work, at least Pounce (Rank 5) and Maim (Rank 2) - i.e. max rank. If you have a lower rank they may not show (i.e. if you're a lower level) - in that case you can always let me know the ids of those auras and I can add them to the database of the AddOn.

Until then I'll close this issue.
